server:
  port: 8088
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/practice?serverTimezone=UTC
    username: cos
    password: cos1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    generate-ddl: true

#jwt:
#  header: ${HEADER}
#  prefix: ${PREFIX}
#  secret: ${SECRET}