server:
  port: 8088
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    generate-ddl: true
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

jwt:
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}
  secretKey: ${JWT_SECRET}
  accessExp: ${ACC_TIME}
  refreshExp: ${REF_TIME}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS}
      secretKey: ${AWS_SECRET}
    s3:
      bucket: ${AWS_BUCKET}
    region:
      static: ${AWS_STATIC}
    stack:
      auto: false
    cloudFront : ${AWS_CLOUD_FRONT}
